repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: ['--django']
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: unittest
        name: UnitTest
        stages: [commit]
        language: system
        entry: "python -B -m coverage run -m unittest"
        types: [python]
        pass_filenames: false
      - id: isort
        name: ISort
        stages: [commit]
        language: system
        entry: "python -B -m isort"
        types: [python]
      - id: tan
        name: Tan
        stages: [commit]
        language: system
        entry: "python -B -m black"
        types: [python]
      - id: flake8
        name: Flake8
        stages: [commit]
        language: system
        entry: "python -B -m flake8"
        types: [python]
      - id: mypy
        name: MyPy
        stages: [commit]
        language: system
        entry: "python -B -m mypy"
        types: [python]
        pass_filenames: false
      - id: coverage
        name: Coverage
        stages: [push]
        language: system
        entry: "python -B -m coverage report"
        types: [python]
        pass_filenames: false
